// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectMetadataPlatform.Infrastructure.DataAccess;

#nullable disable

namespace ProjectMetadataPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectMetadataPlatformDbContext))]
    [Migration("20260609110229_AddEoCAttribute")]
    partial class AddEoCAttribute
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApplicationUserBusinessUnit", b =>
                {
                    b.Property<int>("BusinessUnitsId")
                        .HasColumnType("integer");

                    b.Property<string>("UsersId")
                        .HasColumnType("text");

                    b.HasKey("BusinessUnitsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ApplicationUserBusinessUnit");
                });

            modelBuilder.Entity("ApplicationUserDepartment", b =>
                {
                    b.Property<int>("DepartmentsId")
                        .HasColumnType("integer");

                    b.Property<string>("UsersId")
                        .HasColumnType("text");

                    b.HasKey("DepartmentsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ApplicationUserDepartment");
                });

            modelBuilder.Entity("ApplicationUserTeam", b =>
                {
                    b.Property<int>("TeamsId")
                        .HasColumnType("integer");

                    b.Property<string>("UsersId")
                        .HasColumnType("text");

                    b.HasKey("TeamsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ApplicationUserTeam");
                });

            modelBuilder.Entity("ApplicationUserTeam1", b =>
                {
                    b.Property<int>("TeamSupportId")
                        .HasColumnType("integer");

                    b.Property<string>("TeamSupportUsersId")
                        .HasColumnType("text");

                    b.HasKey("TeamSupportId", "TeamSupportUsersId");

                    b.HasIndex("TeamSupportUsersId");

                    b.ToTable("ApplicationUserTeam1");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.Auth.ApiToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int[]>("Scopes")
                        .HasColumnType("integer[]");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ApiTokens");
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.Auth.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.BusinessUnits.BusinessUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessUnitName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessUnitName")
                        .IsUnique();

                    b.ToTable("BusinessUnits");
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.Companies.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "AppsFactory"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "AppsCompany"
                        });
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.Departments.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentName")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.Logs.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<int?>("AffectedTokenId")
                        .HasColumnType("integer");

                    b.Property<string>("AffectedTokenName")
                        .HasColumnType("text");

                    b.Property<string>("AffectedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("AffectedUserId")
                        .HasColumnType("text");

                    b.Property<string>("AuthorId")
                        .HasColumnType("text");

                    b.Property<string>("AuthorName")
                        .HasColumnType("text");

                    b.Property<int?>("AuthorTokenId")
                        .HasColumnType("integer");

                    b.Property<int?>("BusinessUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("BusinessUnitName")
                        .HasColumnType("text");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("text");

                    b.Property<int?>("GlobalPluginId")
                        .HasColumnType("integer");

                    b.Property<string>("GlobalPluginName")
                        .HasColumnType("text");

                    b.Property<int?>("OfficeLocationId")
                        .HasColumnType("integer");

                    b.Property<string>("OfficeLocationName")
                        .HasColumnType("text");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectName")
                        .HasColumnType("text");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("TeamName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AffectedTokenId");

                    b.HasIndex("AffectedUserId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("AuthorTokenId");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("GlobalPluginId");

                    b.HasIndex("OfficeLocationId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TeamId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.Logs.LogChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LogId")
                        .HasColumnType("integer");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LogId");

                    b.ToTable("LogChange");
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.OfficeLocations.OfficeLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OfficeLocationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OfficeLocationName")
                        .IsUnique();

                    b.ToTable("OfficeLocations");
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.Plugins.Plugin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("PluginName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PluginName")
                        .IsUnique();

                    b.ToTable("Plugins");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            IsArchived = false,
                            PluginName = "Gitlab"
                        },
                        new
                        {
                            Id = 200,
                            IsArchived = false,
                            PluginName = "SonarQube"
                        },
                        new
                        {
                            Id = 300,
                            IsArchived = false,
                            PluginName = "Jira"
                        });
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.Plugins.ProjectPlugins", b =>
                {
                    b.Property<int>("PluginId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.HasKey("PluginId", "ProjectId", "Url");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectPluginsRelation");

                    b.HasData(
                        new
                        {
                            PluginId = 100,
                            ProjectId = 100,
                            Url = "https://http.cat/status/100",
                            DisplayName = "Gitlab"
                        },
                        new
                        {
                            PluginId = 200,
                            ProjectId = 100,
                            Url = "https://http.cat/status/102",
                            DisplayName = "SonarQube"
                        },
                        new
                        {
                            PluginId = 300,
                            ProjectId = 100,
                            Url = "https://http.cat/status/200",
                            DisplayName = "Jira"
                        },
                        new
                        {
                            PluginId = 100,
                            ProjectId = 200,
                            Url = "https://http.cat/status/204",
                            DisplayName = "Gitlab"
                        },
                        new
                        {
                            PluginId = 200,
                            ProjectId = 200,
                            Url = "https://http.cat/status/401",
                            DisplayName = "SonarQube"
                        },
                        new
                        {
                            PluginId = 300,
                            ProjectId = 200,
                            Url = "https://http.cat/status/404",
                            DisplayName = "Jira"
                        },
                        new
                        {
                            PluginId = 100,
                            ProjectId = 300,
                            Url = "https://http.cat/status/406",
                            DisplayName = "Gitlab"
                        },
                        new
                        {
                            PluginId = 200,
                            ProjectId = 300,
                            Url = "https://http.cat/status/411",
                            DisplayName = "SonarQube"
                        },
                        new
                        {
                            PluginId = 300,
                            ProjectId = 300,
                            Url = "https://http.cat/status/414",
                            DisplayName = "Jira"
                        });
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.Projects.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyState")
                        .HasColumnType("integer");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEoC")
                        .HasColumnType("boolean");

                    b.Property<int>("IsmsLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfferId")
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            ClientName = "Deutsche Bahn",
                            CompanyId = 1,
                            CompanyState = 1,
                            IsArchived = false,
                            IsEoC = false,
                            IsmsLevel = 0,
                            Notes = "",
                            OfferId = "Offer1",
                            ProjectName = "DB App",
                            Slug = "db_app"
                        },
                        new
                        {
                            Id = 200,
                            ClientName = "ARD",
                            CompanyId = 2,
                            CompanyState = 0,
                            IsArchived = false,
                            IsEoC = false,
                            IsmsLevel = 1,
                            Notes = "",
                            OfferId = "Offer2",
                            ProjectName = "Tagesschau App",
                            Slug = "tagesschau_app"
                        },
                        new
                        {
                            Id = 300,
                            ClientName = "AOK",
                            CompanyId = 1,
                            CompanyState = 1,
                            IsArchived = false,
                            IsEoC = false,
                            IsmsLevel = 2,
                            Notes = "",
                            OfferId = "Offer3",
                            ProjectName = "AOK Bonus App",
                            Slug = "aok_bonus_app"
                        });
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.Teams.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("PTL")
                        .HasColumnType("text");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("TeamName")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.Users.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsScimProvisioned")
                        .HasColumnType("boolean");

                    b.Property<List<string>>("JobTitles")
                        .HasColumnType("text[]");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("OfficeLocationId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("OfficeLocationId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ApplicationUserBusinessUnit", b =>
                {
                    b.HasOne("ProjectMetadataPlatform.Domain.BusinessUnits.BusinessUnit", null)
                        .WithMany()
                        .HasForeignKey("BusinessUnitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectMetadataPlatform.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationUserDepartment", b =>
                {
                    b.HasOne("ProjectMetadataPlatform.Domain.Departments.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectMetadataPlatform.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationUserTeam", b =>
                {
                    b.HasOne("ProjectMetadataPlatform.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectMetadataPlatform.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationUserTeam1", b =>
                {
                    b.HasOne("ProjectMetadataPlatform.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamSupportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectMetadataPlatform.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("TeamSupportUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProjectMetadataPlatform.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProjectMetadataPlatform.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectMetadataPlatform.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProjectMetadataPlatform.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.Auth.RefreshToken", b =>
                {
                    b.HasOne("ProjectMetadataPlatform.Domain.Users.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.Logs.Log", b =>
                {
                    b.HasOne("ProjectMetadataPlatform.Domain.Auth.ApiToken", "AffectedToken")
                        .WithMany()
                        .HasForeignKey("AffectedTokenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectMetadataPlatform.Domain.Users.ApplicationUser", "AffectedUser")
                        .WithMany()
                        .HasForeignKey("AffectedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectMetadataPlatform.Domain.Users.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectMetadataPlatform.Domain.Auth.ApiToken", "AuthorToken")
                        .WithMany()
                        .HasForeignKey("AuthorTokenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectMetadataPlatform.Domain.BusinessUnits.BusinessUnit", "BusinessUnit")
                        .WithMany()
                        .HasForeignKey("BusinessUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectMetadataPlatform.Domain.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectMetadataPlatform.Domain.Departments.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectMetadataPlatform.Domain.Plugins.Plugin", "GlobalPlugin")
                        .WithMany()
                        .HasForeignKey("GlobalPluginId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectMetadataPlatform.Domain.OfficeLocations.OfficeLocation", "OfficeLocation")
                        .WithMany()
                        .HasForeignKey("OfficeLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectMetadataPlatform.Domain.Projects.Project", "Project")
                        .WithMany("Logs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectMetadataPlatform.Domain.Teams.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AffectedToken");

                    b.Navigation("AffectedUser");

                    b.Navigation("Author");

                    b.Navigation("AuthorToken");

                    b.Navigation("BusinessUnit");

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("GlobalPlugin");

                    b.Navigation("OfficeLocation");

                    b.Navigation("Project");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.Logs.LogChange", b =>
                {
                    b.HasOne("ProjectMetadataPlatform.Domain.Logs.Log", "Log")
                        .WithMany("Changes")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Log");
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.Plugins.ProjectPlugins", b =>
                {
                    b.HasOne("ProjectMetadataPlatform.Domain.Plugins.Plugin", "Plugin")
                        .WithMany("ProjectPlugins")
                        .HasForeignKey("PluginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectMetadataPlatform.Domain.Projects.Project", "Project")
                        .WithMany("ProjectPlugins")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plugin");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.Projects.Project", b =>
                {
                    b.HasOne("ProjectMetadataPlatform.Domain.Companies.Company", "Company")
                        .WithMany("Projects")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectMetadataPlatform.Domain.Teams.Team", "Team")
                        .WithMany("Projects")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.Teams.Team", b =>
                {
                    b.HasOne("ProjectMetadataPlatform.Domain.BusinessUnits.BusinessUnit", "BusinessUnit")
                        .WithMany("Teams")
                        .HasForeignKey("BusinessUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessUnit");
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.Users.ApplicationUser", b =>
                {
                    b.HasOne("ProjectMetadataPlatform.Domain.Companies.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectMetadataPlatform.Domain.OfficeLocations.OfficeLocation", "OfficeLocation")
                        .WithMany("Users")
                        .HasForeignKey("OfficeLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("OfficeLocation");
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.BusinessUnits.BusinessUnit", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.Companies.Company", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.Logs.Log", b =>
                {
                    b.Navigation("Changes");
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.OfficeLocations.OfficeLocation", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.Plugins.Plugin", b =>
                {
                    b.Navigation("ProjectPlugins");
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.Projects.Project", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("ProjectPlugins");
                });

            modelBuilder.Entity("ProjectMetadataPlatform.Domain.Teams.Team", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
