stages:
  - test
  - build
  - deploy

variables:
  DEVELOP_BRANCH: develop

include:
  - project: 'projekt2024_A_Appsfactory_Project_Metadata_Platform/templates'
    ref: main
    file: 'pipeline/all.yml'

prettier:
  script:
    - rm -rf node_modules && yarn install --frozen-lockfile
    - npx prettier --check .

test:
  stage: test
  image: node:latest
  script:
    - rm -rf node_modules && yarn install --frozen-lockfile
    - yarn test --reporter=junit --outputFile=./junit.xml 
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
      junit:
        - junit.xml

code-quality:
  stage: test
  image: node:latest
  script:
    - rm -rf node_modules && yarn install --frozen-lockfile
    - npx eslint --format gitlab .
  allow_failure: true
  artifacts:
    reports:
      codequality: gl-codequality.json
