stages:
  - test
  - sonarqube
  - build
  - deploy

variables:
  DEVELOP_BRANCH: develop

include:
  - project: 'projekt2024_A_Appsfactory_Project_Metadata_Platform/templates'
    ref: main
    file: 'pipeline/all.yml'

test:
  stage: test
  image: node:latest
  script:
    - npm install
    - npm run test -- --reporter=junit --outputFile=./junit.xml
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml

sonarqube:
  stage: sonarqube
  image: 
    name: sonarsource/sonar-scanner-cli:5.0
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH == $DEVELOP_BRANCH