stages:
  - test
  - build
  - deploy

variables:
  DEVELOP_BRANCH: develop

include:
  - project: 'projekt2024_A_Appsfactory_Project_Metadata_Platform/templates'
    ref: main
    file: 'pipeline/all.yml'

test:
  stage: test
  image: node:latest
  script:
    - npm install --legacy-peer-deps
    - npm run test -- --reporter=junit --outputFile=./junit.xml
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml

code-quality:
  stage: test
  image: node:latest
  script:
    - npm install --legacy-peer-deps
    - npx eslint --format gitlab .
  allow_failure: true
  artifacts:
    reports:
      codequality: gl-codequality.json
