stages:
  - test
  - build
  - deploy

default:
  image: node:20-alpine
  before_script:
    # Install yarn as outlined in (https://yarnpkg.com/lang/en/docs/install/#alternatives-stable)
    - npm install -g corepack
    - corepack enable
    - yarn set version stable
    - yarn install --immutable --immutable-cache --check-cache
  cache:
    paths:
      - .yarn
      - node_modules

variables:
  DEVELOP_BRANCH: develop

include:
  - project: 'projekt2024_A_Appsfactory_Project_Metadata_Platform/templates'
    ref: main
    file: 'pipeline/all.yml'

prettier:
  script:
    - npx prettier --check .

test:
  stage: test
  image: node:latest
  script:
    - yarn test --reporter=junit --outputFile=./junit.xml 
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
      junit:
        - junit.xml

code-quality:
  stage: test
  script:
    - npx eslint --format gitlab .
  allow_failure: true
  artifacts:
    reports:
      codequality: gl-codequality.json
