services:
  frontend:
    image: gitlab.dit.htwk-leipzig.de:5050/projekt2024_a_appsfactory_project_metadata_platform/frontend/staging:latest
    container_name: frontend-staging
    networks:
      - frontend-staging
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend-staging.rule=Host(`www.staging.htwk.appsfactory.app`)
      - traefik.http.routers.frontend-staging.entrypoints=websecure
      - traefik.http.routers.frontend-staging.tls.certresolver=le-tls
      - traefik.http.services.frontend-staging-service.loadbalancer.server.port=80

networks:
  frontend-staging:
    name: frontend-staging
    driver: bridge
