services:
  backend:
    image: gitlab.dit.htwk-leipzig.de:5050/projekt2024_a_appsfactory_project_metadata_platform/backend/staging:latest
    container_name: backend-staging
    ports:
      - 8090:8080
    environment:
      - PMP_DB_URL=db-staging
      - PMP_DB_USER_FILE=/run/secrets/db_user
      - PMP_DB_PASSWORD_FILE=/run/secrets/db_password
      - PMP_DB_NAME_FILE=/run/secrets/db_name
      - PMP_DB_PORT=5432
    networks:
      - backend-staging
    secrets:
      - db_user
      - db_password
      - db_name
  
  db:
    image: postgres:15
    container_name: db-staging
    environment:
      - POSTGRES_USER_FILE=/run/secrets/db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_DB_FILE=/run/secrets/db_name
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend-staging
    secrets:
      - db_user
      - db_password
      - db_name

secrets:
  db_password:
    file: db_password.txt
  db_user:
    file: db_user.txt
  db_name:
    file: db_name.txt

volumes:
  db_data:
    
networks:
  backend-staging:
    driver: bridge