# Backend and database service for local frontend development
services:
  backend:
    image: appsfactorylej/project-metadata-platform:dev
    container_name: backend-local
    depends_on:
      - db
    ports:
      - 8090:8080
    environment:
      - PMP_DB_URL=db-local
      - PMP_DB_USER=postgres
      - PMP_DB_PASSWORD=postgres
      - PMP_DB_NAME=pmp_db_local
      - PMP_DB_PORT=5432
      - PMP_MIGRATE_DB_ON_STARTUP=true
      - JWT_VALID_ISSUER=validIssue
      - JWT_VALID_AUDIENCE=validAudience
      - JWT_ISSUER_SIGNING_KEY=superSecretKeyThatIsAtLeast257BitLong@345
      - REFRESH_TOKEN_EXPIRATION_HOURS=6
      - ACCESS_TOKEN_EXPIRATION_MINUTES=15
    networks:
      - backend-local

  db:
    image: postgres:15
    container_name: db-local
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pmp_db_local
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend-local

volumes:
  db_data:

networks:
  backend-local:
    driver: bridge
