/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    PluginComponent: typeof import('./../src/components/Plugin/PluginComponent.vue')['default']
    ProjectInformation: typeof import('./../src/components/ProjectInformation/ProjectInformation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchableTable: typeof import('./../src/components/Table/SearchableTable.vue')['default']
  }
}
