# Database and Cerbos PDP services for local development
services:
  db:
    image: postgres:18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pmp_db_local
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql
      - ./init-cerbos.sql:/docker-entrypoint-initdb.d/init-cerbos.sql

  cerbos:
    image: ghcr.io/cerbos/cerbos:latest
    ports:
      - "3592:3592" # gRPC port
      - "3593:3593" # HTTP port
    command:
      - server
      - --set=storage.driver=postgres
      - --set=storage.postgres.url=postgres://cerbos_user:changeme@db:5432/pmp_db_local?sslmode=disable&search_path=cerbos
    depends_on:
      - db

volumes:
  db_data:
