# Database and Cerbos PDP services for local development
services:
  db:
    image: postgres:18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pmp_db_local
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql
  cerbos:
    image: ghcr.io/cerbos/cerbos:latest
    restart: unless-stopped
    ports:
      - "3592:3592" # gRPC port
      - "3593:3593" # HTTP port
    command:
      - server
      - --set=storage.driver=postgres
      - --set=storage.postgres.url=postgres://postgres:postgres@db:5432/pmp_db_local?sslmode=disable&search_path=cerbos
      - --set=server.adminAPI.enabled=true
      - --set=server.adminAPI.adminCredentials.username=cerbos_user
      - --set=server.adminAPI.adminCredentials.passwordHash=JDJ5JDEwJHl2ZjJJRERFS3VES2FTcExZU2xacmU5a1lLZHA0Z2FnL2c4VU8yaTguZnpacUo3emozSk4yCgo=
    depends_on:
      - db

volumes:
  db_data:
