name: Build_and_Deploy_Project

on:
  workflow_run:
    workflows:
      - Unit_Tests_and_SonarCloud_Analysis
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate date tag using Ubuntu 'date' command
        id: date
        run: echo "tag=$(date +'%Y.%m.%d-%H.%M')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:prod
            ghcr.io/${{ github.repository }}:${{ steps.date.outputs.tag }}
          build-args: |
            BUILD_CONFIGURATION=Release

  deploy-to-prod:
    name: Deploy to Production VM
    needs: build-and-push # Ensures this job runs only after build-and-push succeeds
    environment: production
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Copy compose file to VM
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          source: "docker-compose-production.yml"
          target: "~/pmp-backend/"

      - name: Deploy on VM via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          envs: PMP_DB_USER,PMP_DB_PASSWORD,PMP_DB_NAME,JWT_ISSUER_SIGNING_KEY,PMP_ADMIN_PASSWORD
          script: |
            # Replace placeholders in the compose file with secret values
            sed -i -e "s/{PMP_DB_USER}/${PMP_DB_USER}/g" -e "s/{PMP_DB_PASSWORD}/${PMP_DB_PASSWORD}/g" -e "s/{PMP_DB_NAME}/${PMP_DB_NAME}/g" -e "s/{JWT_ISSUER_SIGNING_KEY}/${JWT_ISSUER_SIGNING_KEY}/g" -e "s/{PMP_ADMIN_PASSWORD}/${PMP_ADMIN_PASSWORD}/g" ~/pmp-backend/docker-compose-production.yml

            # Pull the latest prod image and restart the services
            docker compose -f ~/pmp-backend/docker-compose-production.yml pull
            docker compose -f ~/pmp-backend/docker-compose-production.yml up -d
        env:
          # These secrets are passed as environment variables to the sed command
          PMP_DB_USER: ${{ secrets.PMP_DB_USER }}
          PMP_DB_PASSWORD: ${{ secrets.PMP_DB_PASSWORD }}
          PMP_DB_NAME: ${{ secrets.PMP_DB_NAME }}
          JWT_ISSUER_SIGNING_KEY: ${{ secrets.JWT_ISSUER_SIGNING_KEY }}
          PMP_ADMIN_PASSWORD: ${{ secrets.PMP_ADMIN_PASSWORD }}