name: Backend_Unit_Tests

env:
  DOTNET_VERSION: "10.0.x"
defaults:
  run:
    working-directory: src/backend
on:

  push:
    paths:
      - "src/backend/**"
    branches:
      - main
  pull_request:

    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore packages (dotnet restore)
        run: dotnet restore

      - name: Restore .NET tools (dotnet tool restore)
        run: dotnet tool restore

      - name: Install CSharpier global tool
        run: |
          dotnet tool install --global csharpier
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Verify Formatting with CSharpier
        run: csharpier check ${{ github.workspace }}

      - name: Install dotnet-coverage global tool
        run: dotnet tool install --global dotnet-coverage --version 18.*

      - name: Build project
        run: dotnet build --no-restore --configuration Release

      - name: Run tests and collect coverage
        run: dotnet tool run dotnet-coverage collect "dotnet test --no-build
          --no-restore --configuration Release" -f xml -o "coverage.xml"
